/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: src/object.proto */

#ifndef PROTOBUF_C_src_2fobject_2eproto__INCLUDED
#define PROTOBUF_C_src_2fobject_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Point Point;


/* --- enums --- */


/* --- messages --- */

struct  _Point
{
  ProtobufCMessage base;
  /*
   * A world coordinate point with coordinates (x, y, z) and object ID 
   */
  double x;
  double y;
  double z;
  int32_t obj_id;
};
#define POINT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&point__descriptor) \
    , 0, 0, 0, 0 }


/* Point methods */
void   point__init
                     (Point         *message);
size_t point__get_packed_size
                     (const Point   *message);
size_t point__pack
                     (const Point   *message,
                      uint8_t             *out);
size_t point__pack_to_buffer
                     (const Point   *message,
                      ProtobufCBuffer     *buffer);
Point *
       point__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   point__free_unpacked
                     (Point *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Point_Closure)
                 (const Point *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor point__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_src_2fobject_2eproto__INCLUDED */
