/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: src/object.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "src/object.pb-c.h"
void   point__init
                     (Point         *message)
{
  static Point init_value = POINT__INIT;
  *message = init_value;
}
size_t point__get_packed_size
                     (const Point *message)
{
  assert(message->base.descriptor == &point__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t point__pack
                     (const Point *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &point__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t point__pack_to_buffer
                     (const Point *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &point__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Point *
       point__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Point *)
     protobuf_c_message_unpack (&point__descriptor,
                                allocator, len, data);
}
void   point__free_unpacked
                     (Point *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &point__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor point__field_descriptors[4] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Point, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Point, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "z",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Point, z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "obj_id",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    offsetof(Point, obj_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned point__field_indices_by_name[] = {
  3,   /* field[3] = obj_id */
  0,   /* field[0] = x */
  1,   /* field[1] = y */
  2,   /* field[2] = z */
};
static const ProtobufCIntRange point__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor point__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Point",
  "Point",
  "Point",
  "",
  sizeof(Point),
  4,
  point__field_descriptors,
  point__field_indices_by_name,
  1,  point__number_ranges,
  (ProtobufCMessageInit) point__init,
  NULL,NULL,NULL    /* reserved[123] */
};
